name: Run Batch Scraper and Save Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Batch Scraper
      run: |
        python app/batch_scrape.py

    - name: Commit and Push Results
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add scraped_data.json scraped_data.csv
        git commit -m "Add scraped data files"
        git push
      env:
        # Provide the GitHub token to allow pushing changes
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
